##############################################################################################
# knotAnnotSV 1.0                                                                            #	
#                                                                                            #
# knotAnnotSV: Creation of a customizable html file to visualize, filter                     # 
#                   and analyze an AnnotSV output                                            #
#                                                                                            #
# Author: Thomas Guignard 2020                                                               #
#                                                                                            #
# Copyright (C) 2020 Thomas Guignard (t-guignard@chu-montpellier.fr)                         #
#                                                                                            #
# This is part of knotAnnotSV source code.                                                   #
#                                                                                            #
# This program is free software; you can redistribute it and/or                              #
# modify it under the terms of the GNU General Public License                                #
# as published by the Free Software Foundation; either version 3                             #
# of the License, or (at your option) any later version.                                     #
#                                                                                            #
# This program is distributed in the hope that it will be useful,                            #
# but WITHOUT ANY WARRANTY; without even the implied warranty of                             #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                              #
# GNU General Public License for more details.                                               #
#                                                                                            #
# You should have received a copy of the GNU General Public License                          #
# along with this program; If not, see <http://www.gnu.org/licenses/>.                       #
##############################################################################################
---
AnnotSV ID:    #mandatory
    POSITION: 1
    COMMENTLIST:
        - SV length
        - SV type
AnnotSV ranking:  # mandatory
    POSITION: 2
SV chrom:
    POSITION: 0
#SV start:
#    POSITION: 0
SV end:
    POSITION: 0
SV length:
    POSITION: 0
SV type:
    POSITION: 3
Samples_ID:
    POSITION: 0
REF:
    POSITION: 0
ALT:
    POSITION: 0
FORMAT:
    POSITION: 0
Sample ID:
    POSITION: 0
AnnotSV type:
    POSITION: 4 #should be kept  //// specify mandatory fields for good computing
Gene name:     # mandatory
    POSITION: 5
    COMMENTLIST:
        - pLI_ExAC
        - HI_CGscore
        - TriS_CGscore 
        - HI_DDDpercent
        - ACMG
        - cnvZ_ExAC
        - delZ_ExAC
        - dupZ_ExAC
        - synZ_ExAC
        - misZ_ExAC
    RENAME: Some Genes
    HEADERTIPS: Provided by OMIM        
tx:
    POSITION: 0
CDS length:
    POSITION: 0
tx length:
    POSITION: 0
location:
    POSITION: 6
    RENAME: Location Genes
    HEADERTIPS: Provided by OMIM        
morbidGenes:
    POSITION: 7
    COMMENTLIST:
        - Mim Number
        - Phenotypes
        - Inheritance
        - morbidGenesCandidates
    RENAME: Morbid Genes
    HEADERTIPS: Provided by OMIM        
EXOMISER_GENE_PHENO_SCORE:
    POSITION: 8
    COMMENTLIST:
        - HUMAN_PHENO_EVIDENCE
        - MOUSE_PHENO_EVIDENCE
        - FISH_PHENO_EVIDENCE
dbVar_status:
    POSITION: 9
    COMMENTLIST:
        - dbVar_event
        - dbVar_variant
location2:
    POSITION: 0
intersectStart:
    POSITION: 0
intersectEnd:
    POSITION: 0
DGV_GAIN_IDs:
    POSITION: 0
DGV_GAIN_n_samples_with_SV:
    POSITION: 0
DGV_GAIN_n_samples_tested:
    POSITION: 0
DGV_GAIN_Frequency:
    POSITION: 10 
    COMMENTLIST:
        - DGV_GAIN_n_samples_with_SV
        - DGV_GAIN_n_samples_tested
        - DGV_LOSS_Frequency
        - DGV_LOSS_n_samples_with_SV
        - DGV_LOSS_n_samples_tested
DGV_LOSS_IDs:
    POSITION: 0
DGV_LOSS_n_samples_with_SV:
    POSITION: 0
DGV_LOSS_n_samples_tested:
    POSITION: 0
DGV_LOSS_Frequency:
    POSITION: 0
DDD_SV:
    POSITION: 0
DDD_DUP_n_samples_with_SV:
    POSITION: 0
DDD_DUP_Frequency:
    POSITION: 11
    COMMENTLIST:
        - DDD_DUP_n_samples_with_SV
        - DDD_DEL_Frequency
        - DDD_DEL_n_samples_with_SV
        - DDD_status
        - DDD_mode
        - DDD_consequence 
DDD_DEL_n_samples_with_SV:
    POSITION: 0
DDD_DEL_Frequency:
    POSITION: 0
DDD_status:
    POSITION: 0 
GD_ID:
    POSITION: 0
GD_AN:
    POSITION: 0
GD_N_HET:
    POSITION: 0
GD_N_HOMALT:
    POSITION: 0
GD_AF:
    POSITION: 0
GD_POPMAX_AF:
    POSITION: 12
    COMMENTLIST:
        - GD_AN
        - GD_N_HET
        - GD_N_HOMALT
        - GD_AF
GD_ID_others:
    POSITION: 0
1000g_event:
    POSITION: 0
IMH_ID:
    POSITION: 0
IMH_AF:
    POSITION: 13
IMH_ID_others:
    POSITION: 0
promoters:
    POSITION: 14
    COMMENTLIST:
        - TADcoordinates
#        - GHid_elite
#        - GHid_not_elite
#        - GHtype
#        - GHgene_elite
#        - GHgene_not_elite
#        - GHtissue
dbVar_event:
    POSITION: 0
dbVar_variant:
    POSITION: 0
GHid_elite:
    POSITION: 0
GHid_not_elite:
    POSITION: 0
GHtype:
    POSITION: 0
GHgene_elite:
    POSITION: 0
GHgene_not_elite:
    POSITION: 0
GHtissue:
    POSITION: 0
COSMIC_ID:
    POSITION: 0
COSMIC_MUT_TYP:
    POSITION: 0
TADcoordinates:
    POSITION: 0
ENCODEexperiments:
    POSITION: 0
GCcontent_right:
    POSITION: 0
GCcontent_left:
    POSITION: 0
Repeats_coord_left:
    POSITION: 0
Repeats_type_left:
    POSITION: 0
Repeats_coord_right:
    POSITION: 0
Repeats_type_right:
    POSITION: 0
ACMG:
    POSITION: 0
HI_CGscore:
    POSITION: 0
TriS_CGscore:
    POSITION: 0
DDD_mode:
    POSITION: 0
DDD_consequence:
    POSITION: 0
DDD_pmids:
    POSITION: 0
HI_DDDpercent:
    POSITION: 0
synZ_ExAC:
    POSITION: 0
misZ_ExAC:
    POSITION: 0
pLI_ExAC:
    POSITION: 0
delZ_ExAC:
    POSITION: 0
dupZ_ExAC:
    POSITION: 0
cnvZ_ExAC:
    POSITION: 0
morbidGenesCandidates:
    POSITION: 0
Mim Number:
    POSITION: 0
Phenotypes:
    POSITION: 0
Inheritance:
    POSITION: 0
HUMAN_PHENO_EVIDENCE:
    POSITION: 0
MOUSE_PHENO_EVIDENCE:
    POSITION: 0
FISH_PHENO_EVIDENCE:
    POSITION: 0
compound-htz(sample):
    POSITION: 0
#hom(sample):
    POSITION: 0
#htz(sample):
    POSITION: 0
#htz/allHom(sample):
    POSITION: 0
#htz/total(cohort):
    POSITION: 0
#total(cohort):
    POSITION: 0


